[package]
authors = ["Harald Niesche <harald@niesche.de>"]
edition = "2018"
name = "diagnostics-service"
version = "0.1.0"

[dependencies]
actix-web = "3.1.0"
chrono = "0.4.19"

[dependencies.async-std]
version = "1.6.5"
features = [ "unstable", "tokio02" ]
